### ISSUE TITLE
h2>1

### ISSUE THREAD

**Issue by e-manduchi** [omerwe/LEAP#5]
hello,
I've been recently using LEAP on two data sets on which it seems to have run without problems. I'm now trying it on a third data set but on this one I get h2 values >1 (as per below log). This consequently generates problems when I run probit.py:

/home/manduchi/mypy/lib/python2.7/site-packages/leap/probit.py:57: RuntimeWarning: invalid value encountered in sqrt
  normPDF = stats.norm(0, np.sqrt(1-h2))
...

Can you advice?
Thanks,
Elisabetta

=== calc_h2.py run
 python calc_h2.py --bfilesim data_autosome --prev 0.1 --pheno leap.phe --eigen leap_noChr1.kin.npz --extractSim noChr1.snps --related leap.rm
/home/
manduchi/mypy/lib/python2.7/site-packages/pysnptools/snpreader/bed.py:42: FutureWarning: 'count_A1' was not set. For now it will default to 'False', but in the future it will default to 'True'
  warnings.warn("'count_A1' was not set. For now it will default to 'False', but in the future it will default to 'True'", FutureWarning)
WARNING:root:loadPhen is using default missing value of '-9'.
WARNING:root:loadPhen is using default missing value of '-9'.
29 individuals will be removed due to high relatedness
Removing the top 10 PCs from the kinship matrix
Computing h2 for a binary phenotype
h2: 1.241879

**Comment by omerwe** [comment]
Hi Elisabetta,

Thanks for using LEAP!
LEAP estimates heritability by using PCGC (Golan, Lander and Rosset, PNAS
2014) <http://www.pnas.org/content/111/49/E5272.short>. Indeed, the PCGC
estimatror can sometimes estimate h2>1 for small datasets. This can happen
under model misspecification (e.g. incorrect prevalence estimate), but it
can also happen simply due to sampling variance, especially with small
datasets (i.e., <5000 individuals).

Unfortunately, there is no simple solution for this. I would start by
double checking the prevalence estimate and all the other input. If you're
sure that everything is correct, then a possible solution is to assume that
the SNP heritability is truly close to 100%. In this case, you could input
99% or a similar number to calc_h2.py, under the assumption that this is
the true underlying SNP heritability.

Good luck, and do not hesitate if you have any other questions!

Best,

Omer

**Comment by e-manduchi** [comment]
Hello Omer,
thanks for your prompt reply!
Regarding prevalence, since from the literature I saw that the prevalence of my trait of interest is 10%, I've simply entered '--prev 0.1'  in my runs. Is this correct, or should I have entered another value (like liability threshold)?
My population is just short of 5000 individuals, but I've run LEAP on two other data sets (one much smaller) for the same trait (using the same --prev of 0.1) and it didn't throw errors. The h2 estimated by calc_h2 on these data  sets was between 0.2 and 0.24 depending on chromosome.
Elisabetta

**Comment by omerwe** [comment]
Hi Elisabetta,

What you did sounds perfectly fine.
Is your population a "natural population"? LEAP isn't necessarily suitable
for inbred populations, such as mice crosses.
Another possibility is that the h2 estimate in these datasets is noisy. My
code estimates h2, but unfortunately it doesn't estimate its 95% confidence
interval.

One thing you can try to do is to estimate h2 using gcta
<http://cnsgenomics.com/software/gcta> instead of my own code (using the
--prevalence flag). These estimates are typically down-biased (as shown in
the PCGC paper <http://www.pnas.org/content/111/49/E5272.short> by
Golan et al.), but it may be that for some (strange) reason it will give
more sensible results on this particular data set.

If all else fails, I would just trying running calc_probit with h2=0.95. It
may be sub-optimal, but I think that you can still gain statistical power
in this way over a naive association analysis. However, I should also point
out that according to our simulations in the LEAP paper, the advantage of
using LEAP over a plain LMM analysis under 10% prevalence is not very
large. LEAP becomes significantly more powerful than a standard LMM with
prevalence<1%. Hence, it might not make a large difference anyway whether
you use a LEAP or a plain LMM analysis...

Good luck again, and do not hesitate if you have any other questions!

Omer

**Comment by e-manduchi** [comment]
Thanks for the suggestions and clarifications. Yes, my population is natural, it's a subset of the WTCCC data. I'll try what you indicate and see what happens. Thanks again,
Elisabetta
